# Generated by Django 4.2.2 on 2023-06-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_current_semester'),
        ('student', '0003_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_sign',
            field=models.ImageField(blank=True, null=True, upload_to='sign'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
