# Generated by Django 4.2.2 on 2023-06-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sembook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sembook',
            old_name='priciple',
            new_name='pricipal',
        ),
    ]
