# Generated by Django 4.2.2 on 2023-06-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sembook', '0002_rename_priciple_sembook_pricipal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sembook',
            name='pricipal',
        ),
        migrations.AddField(
            model_name='sembook',
            name='principal_sign',
            field=models.ImageField(blank=True, null=True, upload_to='sembook/principal_sign'),
        ),
    ]
