# Generated by Django 4.2.2 on 2023-06-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_signature'),
        ('sembook', '0003_remove_sembook_pricipal_sembook_principal_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sembook',
            name='principal_sign',
        ),
        migrations.AddField(
            model_name='sembook',
            name='pricipal',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'PRINCIPAL'}, on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
            preserve_default=False,
        ),
    ]
