# Generated by Django 4.2.2 on 2023-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sembook', '0005_rename_pricipal_sembook_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sembook',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
